# Generated by Django 3.1.7 on 2021-02-23 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causa_muerte', '0001_initial'),
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cantidad_muertes', models.IntegerField()),
                ('descrpcion', models.CharField(max_length=100)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='causa_muerte.causa_muerte')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribucion.distribucion')),
            ],
            options={
                'verbose_name': 'mortalidad',
                'verbose_name_plural': 'mortalidades',
                'db_table': 'mortalidad',
                'ordering': ['-id', '-distribucion', 'causa'],
            },
        ),
    ]
