# Generated by Django 3.1.7 on 2021-03-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortalidad',
            name='cantidad_muertes',
            field=models.IntegerField(default=1),
        ),
    ]
