# Generated by Django 3.1.7 on 2021-02-23 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('valor_pollito', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raza.raza')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'db_table': 'lote',
                'ordering': ['-id', '-fecha'],
            },
        ),
    ]
