# Generated by Django 3.1.7 on 2021-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_lote_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='stock_produccion',
            field=models.IntegerField(default=0),
        ),
    ]
