# Generated by Django 3.1.7 on 2021-02-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
        ('galpon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pollos', models.IntegerField(blank=True, default=1, null=True)),
                ('galpon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='galpon.galpon')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lote.lote')),
            ],
            options={
                'verbose_name': 'distribucion',
                'verbose_name_plural': 'distribuciones',
                'db_table': 'distribucion',
                'ordering': ['-lote', '-galpon', 'cantidad_pollos'],
            },
        ),
    ]
