# Generated by Django 3.1.7 on 2021-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='stock_actual',
            field=models.IntegerField(default=1),
        ),
    ]
