# Generated by Django 3.1.7 on 2021-03-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('tipo_medicina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='insumo.insumo')),
                ('tipo_medicina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_medicina.tipo_medicina')),
            ],
            options={
                'verbose_name': 'medicina',
                'verbose_name_plural': 'medicinas',
                'db_table': 'medicina',
                'ordering': ['-id'],
            },
        ),
    ]
