# Generated by Django 3.1.7 on 2021-02-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
        ('medicina', '0002_medicina_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicina',
            options={'ordering': ['-id'], 'verbose_name': 'medicina', 'verbose_name_plural': 'medicinas'},
        ),
        migrations.RemoveField(
            model_name='medicina',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='medicina',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medicina',
            name='precio',
        ),
        migrations.AddField(
            model_name='medicina',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='insumo.insumo'),
        ),
    ]
