# Generated by Django 3.1.7 on 2021-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(default=1)),
                ('estado', models.IntegerField(choices=[(1, 'LABORANDO'), (0, 'DISPONIBLE')], default=1)),
            ],
            options={
                'verbose_name': 'galpon',
                'verbose_name_plural': 'galpones',
                'db_table': 'galpon',
                'ordering': ['-id', '-capacidad'],
            },
        ),
    ]
