# Generated by Django 3.1.7 on 2021-02-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galpon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galpon',
            name='estado',
            field=models.IntegerField(choices=[(1, 'LABORANDO'), (0, 'DISPONIBLE')], default=0),
        ),
    ]
