# Generated by Django 3.1.7 on 2021-03-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentacion', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='insumo.insumo')),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presentacion.presentacion')),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
                'db_table': 'alimento',
                'ordering': ['-id'],
            },
        ),
    ]
