# Generated by Django 3.1.7 on 2021-02-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0002_auto_20210227_1547'),
        ('insumo', '0001_initial'),
        ('presentacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='insumo.insumo'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='presentacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presentacion.presentacion'),
        ),
    ]
