# Generated by Django 3.1.7 on 2021-03-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
        ('gasto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='empresa',
        ),
        migrations.AddField(
            model_name='gasto',
            name='distribucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='distribucion.distribucion'),
        ),
    ]
