# Generated by Django 3.1.7 on 2021-02-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='empresa',
        ),
    ]
