# Generated by Django 3.1.7 on 2021-03-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'canton',
                'verbose_name_plural': 'cantones',
                'db_table': 'canton',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'provincia',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.canton')),
            ],
            options={
                'verbose_name': 'parroquia',
                'verbose_name_plural': 'parroquias',
                'db_table': 'parroquia',
                'ordering': ['-nombre'],
            },
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.provincia'),
        ),
    ]
