# Generated by Django 3.1.7 on 2021-03-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causa_muerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'causa_muerte',
                'verbose_name_plural': 'causa_muertes',
                'db_table': 'causa_muerte',
                'ordering': ['-id', '-nombre'],
            },
        ),
    ]
