# Generated by Django 3.1.7 on 2021-03-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lote.lote')),
            ],
            options={
                'verbose_name': 'produccion',
                'verbose_name_plural': 'producciones',
                'db_table': 'produccion',
                'ordering': ['-id', '-lote'],
            },
        ),
    ]
