# Generated by Django 3.1.7 on 2021-02-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'En stock'), (0, 'Vendido')], default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.detalle_compra')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventario',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
    ]
