# Generated by Django 3.1.7 on 2021-02-23 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('peso_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribucion.distribucion')),
            ],
            options={
                'verbose_name': 'peso',
                'verbose_name_plural': 'pesos',
                'db_table': 'peso',
                'ordering': ['-id', '-distribucion'],
            },
        ),
    ]
