# Generated by Django 3.1.7 on 2021-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20210227_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=9),
        ),
    ]
