# Generated by Django 3.1.7 on 2021-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='jpg',
            field=models.ImageField(blank=True, null=True, upload_to='comprobante/%Y/%m/%d'),
        ),
    ]
