# Generated by Django 3.1.7 on 2021-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_compra_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprobante',
            field=models.TextField(blank=True, null=True),
        ),
    ]
