# Generated by Django 3.1.7 on 2021-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_auto_20210301_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='stock_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='stock_inicial',
            field=models.IntegerField(default=1),
        ),
    ]
