# Generated by Django 3.1.7 on 2021-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'ANULADA'), (1, 'FINALIZADA'), (2, 'RESERVADA')], default=1),
        ),
    ]
