# Generated by Django 3.1.5 on 2021-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.IntegerField(choices=[(0, 'CONTADO'), (1, 'CREDITO')], default=0),
        ),
    ]
