# Generated by Django 3.1.5 on 2021-02-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.IntegerField(choices=[(0, 'FISICA'), (1, 'ONLINE')], default=0),
        ),
    ]
