# Generated by Django 3.1.7 on 2021-03-06 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0001_initial'),
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField(blank=True, default=1, null=True)),
                ('alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alimento.alimento')),
                ('distribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='distribucion.distribucion')),
            ],
            options={
                'verbose_name': 'alimentacion',
                'verbose_name_plural': 'alimentaciones',
                'db_table': 'alimentacion',
                'ordering': ['-id', '-distribucion', '-alimento', 'cantidad'],
            },
        ),
    ]
