# Generated by Django 3.1.7 on 2021-03-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentacion',
            options={'ordering': ['-id', '-distribucion', '-alimento', 'cantidad'], 'verbose_name': 'alimentacion', 'verbose_name_plural': 'alimentaciones'},
        ),
        migrations.RenameField(
            model_name='alimentacion',
            old_name='cantidad_sacos',
            new_name='cantidad',
        ),
    ]
