# Generated by Django 3.1.7 on 2021-03-06 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (0, 'Femenino')], default=1)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('estado', models.IntegerField(choices=[(1, 'LABORANDO'), (0, 'DISPONIBLE')], default=0)),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
                'ordering': ['-nombres', '-apellidos', '-cedula'],
            },
        ),
    ]
