# Generated by Django 3.1.7 on 2021-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.IntegerField(choices=[(3, 'OPERATIVO'), (2, 'VENDEDOR'), (1, 'SECRETARIA'), (0, 'GERENTE')], default=0),
        ),
    ]
