# Generated by Django 3.1.7 on 2021-02-23 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=1)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alimento.alimento')),
            ],
            options={
                'verbose_name': 'provision_alimento',
                'verbose_name_plural': 'provision_alimentos',
                'db_table': 'provision_alimento',
                'ordering': ['-id', '-alimento', '-fecha'],
            },
        ),
    ]
