# Generated by Django 3.1.7 on 2021-03-12 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0002_auto_20210308_1035'),
        ('compra', '0002_compra_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.venta')),
            ],
            options={
                'verbose_name': 'devolucion_venta',
                'verbose_name_plural': 'devolucion_ventas',
                'db_table': 'devolucion_venta',
                'ordering': ['id', 'venta'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compra')),
            ],
            options={
                'verbose_name': 'devolucion_compra',
                'verbose_name_plural': 'devolucion_compras',
                'db_table': 'devolucion_compra',
                'ordering': ['-id', 'compra'],
            },
        ),
    ]
