# Generated by Django 3.1.7 on 2021-03-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=25)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('iva', models.IntegerField(blank=True, default=12, null=True)),
                ('tasa', models.IntegerField(blank=True, default=16, null=True)),
                ('indice', models.IntegerField(blank=True, default=12, null=True)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubicacion.parroquia')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresa',
                'ordering': ['-nombre', '-ruc', '-direccion'],
            },
        ),
    ]
