# Generated by Django 3.1.7 on 2021-06-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_portadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logo'),
        ),
    ]
